apiVersion: apps/v1
kind: Deployment
metadata:
  name: smile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smile
  template:
    metadata:
      labels:
        app: smile
    spec:
      containers:
      - image: okteto.dev/smile:latest
        name: smile
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "2e2fcebe-ecd3-4826-a8de-c259ae154e45"
        - name: Vless_Path
          value: "/syTYrt"
        - name: Vmess_UUID
          value: "2e2fcebe-ecd3-4826-a8de-c259ae154e45"
        - name: Vmess_Path
          value: "/ascuprf"
        - name: Share_Path
          value: "/Share433"
