apiVersion: apps/v1
kind: Deployment
metadata:
  name: erect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erect
  template:
    metadata:
      labels:
        app: erect
    spec:
      containers:
      - image: okteto.dev/erect:latest
        name: erect
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.crazygames.com"
        - name: Vless_UUID
          value: "6db0abfd-6b8d-4c2a-b7e6-462a93677175"
        - name: Vless_Path
          value: "/qftrvu67"
        - name: Vmess_UUID
          value: "6db0abfd-6b8d-4c2a-b7e6-462a93677175"
        - name: Vmess_Path
          value: "/SDFVYJU"
        - name: Share_Path
          value: "/Share312"
