apiVersion: apps/v1
kind: Deployment
metadata:
  name: ywer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ywer
  template:
    metadata:
      labels:
        app: ywer
    spec:
      containers:
      - image: okteto.dev/ywer:latest
        name: ywer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "pixabay.com"
        - name: Vless_UUID
          value: "3d147969-24f3-4760-b093-63b65fac91e1"
        - name: Vless_Path
          value: "/Grtf5utew"
        - name: Vmess_UUID
          value: "3d147969-24f3-4760-b093-63b65fac91e1"
        - name: Vmess_Path
          value: "/LuteFs"
        - name: Share_Path
          value: "/Share579"
