apiVersion: apps/v1
kind: Deployment
metadata:
  name: quaily
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quaily
  template:
    metadata:
      labels:
        app: quaily
    spec:
      containers:
      - image: okteto.dev/quaily:latest
        name: quaily
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.flexclip.com"
        - name: Vless_UUID
          value: "a32b2ac0-1bad-4bcb-a266-66136c5a984a"
        - name: Vless_Path
          value: "/FHOWAS"
        - name: Vmess_UUID
          value: "a32b2ac0-1bad-4bcb-a266-66136c5a984a"
        - name: Vmess_Path
          value: "/CR46yds"
        - name: Share_Path
          value: "/Share021"
