apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
      - image: okteto.dev/cloud:latest
        name: cloud
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "moviesjoy.to"
        - name: Vless_UUID
          value: "30730823-d7e0-4f42-b10a-bc5bb562826c"
        - name: Vless_Path
          value: "/AHtfG6"
        - name: Vmess_UUID
          value: "30730823-d7e0-4f42-b10a-bc5bb562826c"
        - name: Vmess_Path
          value: "/OPRECX"
        - name: Share_Path
          value: "/Share412"
